<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Jackets</name>
   <tag></tag>
   <elementGuidId>96b3c186-5ded-4e23-a69c-8c4471d2d8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.base</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='page-title-heading']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e5a73fa-beed-46a7-a5cb-9b56b3ad93b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base</value>
      <webElementGuid>e20afd9f-bae9-4f11-8b5c-e427f7deac7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-id</name>
      <type>Main</type>
      <value>page-title-wrapper</value>
      <webElementGuid>8a7dfbad-7171-4e55-acf2-3c3d78fe451e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jackets</value>
      <webElementGuid>f395e5b3-ce9c-47bc-a4b3-78aab9c60cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-title-heading&quot;)/span[@class=&quot;base&quot;]</value>
      <webElementGuid>eae7cb44-f054-4da3-8863-cb5b8776296a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='page-title-heading']/span</value>
      <webElementGuid>cfb5d518-c2d4-43f2-9b32-4251e3e9bf96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jackets'])[3]/following::span[1]</value>
      <webElementGuid>8b674a1f-295f-45fb-8c06-4a186ea9be45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[3]/following::span[1]</value>
      <webElementGuid>bc979c85-9c66-418f-9acb-98e984e1a2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View as'])[1]/preceding::span[1]</value>
      <webElementGuid>36c377dc-87c1-4850-8ca8-c22bf5e0b884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grid'])[1]/preceding::span[1]</value>
      <webElementGuid>9af39876-d4fd-442b-bccd-8cbf1209c74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>46d9d7d5-1f43-4dd6-9aa6-0e3db5373278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Jackets' or . = 'Jackets')]</value>
      <webElementGuid>b5998e01-d1db-4d92-9dec-d08d578d675e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
