<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Women</name>
   <tag></tag>
   <elementGuidId>b234eb54-5c4e-4d6c-a150-57f7d45e8ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d86fe963-20c5-4891-9b02-6eb89a6140e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/women.html</value>
      <webElementGuid>2a00e272-f482-4b2c-9f89-c3f51c2f43d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>level-top ui-corner-all</value>
      <webElementGuid>703049de-e254-4b95-b2ba-290ac7311b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aed900f9-9733-46b2-b414-5b6f259b802b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-4</value>
      <webElementGuid>175aa646-1f28-4c35-94dd-80723dfdbecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c1861b14-573e-46c4-9c5a-9caefb848284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>aa6143be-e831-4b51-8aea-c48357126b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Women</value>
      <webElementGuid>8e17948d-0a16-4baa-aa59-9269b7525b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-4&quot;)</value>
      <webElementGuid>10a61b77-8e3b-4831-adc7-a25862a7267e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-4']</value>
      <webElementGuid>6f84ed24-b249-4bcf-af1b-a4b2c132ebdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-2']/li[2]/a</value>
      <webElementGuid>59117649-f207-4a2e-8884-5ede77c1861a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('What', &quot;'&quot;, 's New')])[1]/following::a[1]</value>
      <webElementGuid>e4cc6b26-dd38-49e4-a8b0-58eb3a3966c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::a[2]</value>
      <webElementGuid>a88c056b-bf8e-40e4-9596-d246fc68c148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[1]/preceding::a[1]</value>
      <webElementGuid>8e48c128-3747-46b7-bc2d-6a51fe7ad59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://magento.softwaretestingboard.com/women.html')]</value>
      <webElementGuid>8c552238-4c85-4eb1-b7d5-75fe039c840c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>45958708-bf5c-4f08-bcdb-a111da131774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://magento.softwaretestingboard.com/women.html' and @id = 'ui-id-4' and (text() = 'Women' or . = 'Women')]</value>
      <webElementGuid>5b9e0189-f9d0-483c-9d87-e40b553e49d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
