<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_is Subscribed</name>
   <tag></tag>
   <elementGuidId>1a234909-eaed-448a-a18d-cf678730c875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is_subscribed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_subscribed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>612a786b-b9d9-43e0-b609-0e04f3b27146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8e889936-184b-4621-b589-0ce380cdb303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_subscribed</value>
      <webElementGuid>ce67570a-f54c-4d69-bc4f-a15af2303dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign Up for Newsletter</value>
      <webElementGuid>03d5f033-0db5-4356-8c23-1fc77b108d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9819b362-2956-447b-8b5f-f6eabf9cc241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_subscribed</value>
      <webElementGuid>2d7b4a8e-e468-44f7-a21f-c23133d4160b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9f9a41de-d2a0-4494-99ad-69c5373446b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_subscribed&quot;)</value>
      <webElementGuid>58c317e7-5c73-47dd-a68d-66a1c4fc1e88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_subscribed']</value>
      <webElementGuid>918c6ed4-f806-447e-8cd6-e8c437f15207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset/div[3]/input</value>
      <webElementGuid>fc98013a-84aa-4e08-bf3d-ef991c58a551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>1d593fac-261b-4f9a-8990-05d121283ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_subscribed' and @title = 'Sign Up for Newsletter' and @id = 'is_subscribed']</value>
      <webElementGuid>b21b3792-f7b8-4f50-91f1-7ffc52ca5b1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
