<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Jackets</name>
   <tag></tag>
   <elementGuidId>1b4f18d7-e9d2-4793-bced-614547cec4fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.base</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='page-title-heading']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3d6bfdeb-d113-46cc-8975-e77a686e0ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base</value>
      <webElementGuid>feb92b27-acff-4243-a14f-0c66b235a08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-id</name>
      <type>Main</type>
      <value>page-title-wrapper</value>
      <webElementGuid>6ceee63b-a038-40e2-9008-c9c8d0cb6fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jackets</value>
      <webElementGuid>3a4ae058-263b-496b-a854-45c7ccebaeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-title-heading&quot;)/span[@class=&quot;base&quot;]</value>
      <webElementGuid>c181a08f-3ade-46f0-9b6e-9cdcb4943878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='page-title-heading']/span</value>
      <webElementGuid>e2a924e2-94a0-4a81-a7f9-dbd6d235567a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jackets'])[3]/following::span[1]</value>
      <webElementGuid>93971e5a-bcf4-4aff-a9d3-bb85a629904b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[3]/following::span[1]</value>
      <webElementGuid>8c9a80b1-f511-4897-b7ec-8e1b982d9541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View as'])[1]/preceding::span[1]</value>
      <webElementGuid>b5800da7-f11c-4855-b1b0-f1c110137cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grid'])[1]/preceding::span[1]</value>
      <webElementGuid>bf8f8104-60f0-4a5d-a23b-983db6209fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>4620b0b7-b70c-4b1b-8800-13afa48080cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Jackets' or . = 'Jackets')]</value>
      <webElementGuid>1d794fb7-adfc-4242-8e60-47e01f472062</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
